### ISSUE TITLE
GLIBC version not found error on Ubuntu and on Ubuntu WSL2

### ISSUE THREAD

**Issue by daangemist** [julien040/anyquery#12]
I tried to install anyquery on my Ubuntu server using `apt-get` and in WSL2 in Windows (Ubuntu), but for both installations got this error when running `anyquery`:

```
dan@LAPTOP:~$ anyquery
anyquery: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by anyquery)
```

What am I missing here, is there something outdated on my OS(es)?

**Comment by julien040** [comment]
Hi, which version of Ubuntu are you using?
Anyquery is compiled against Ubuntu 24.04. That might be the issue.

You can check the version using this command `lsb_release -a`. If possible, try to update Ubuntu by following [this link](https://askubuntu.com/questions/1428423/upgrade-ubuntu-in-wsl2-from-20-04-to-22-04)

**Comment by julien040** [comment]
Hi @daangemist, just following up. Have you been able to fix the issue?

**Comment by daangemist** [comment]
Apologies, I missed the notification that you replied to the ticket. I indeed have a different Ubuntu version, 22.04.3 LTS on WSL2 and the server. Do you know of a way to run _anyquery_ on it without having to upgrade the OS?

**Comment by julien040** [comment]
No worries. I've published a new version (`0.1.3`) that should fix the issue. To download it, run:

```bash
sudo apt update
sudo apt install anyquery
```

Let me know if it fixes the issue.

> **Nerdy details**
> Anyquery is now compiled using `musl-gcc` on `amd64`. It therefore doesn't need glibc anymore and fixes the glibc compatibility issue.

**Comment by daangemist** [comment]
Yes, that fixes the issue! Thanks a lot :-) 

I recorded my podcast today where I mentioned this issue with anyquery, but I'll make sure to add to the notes that it has already been resolved swiftly!

**Comment by julien040** [comment]
Thank you for mentioning Anyquery!
