### ISSUE TITLE
Cannot use CTE and read_html() function 

### ISSUE THREAD

**Issue by marcoarthur** [julien040/anyquery#17]
Trying to select more than one selector I wrote the following CTE
But, anyquery returned this error:
<pre>
anyquery> WITH files AS (
.........   SELECT * FROM read_html('http://localhost:8000/', '.mtime')
.........   UNION
.........   SELECT * FROM read_html('http://localhost:8000/', '.size')
......... )
......... SELECT * 
......... FROM files;
no such table: read_html
anyquery> 
</pre>

But I am able to run the SELECT outside the CTE:
<pre>
anyquery> SELECT * FROM read_html('http://localhost:8000/', '.mtime');
+----------+-------------------------------+--------------------------------------+
| tag_name |            content            |              attributes              |
+----------+-------------------------------+--------------------------------------+
| td       | Wed, 21 Aug 2024 14:13:54 GMT | [{"Namespace":"","Key":"class","Val" |
|          |                               | :"mtime"}]                           |
| td       | Wed, 21 Aug 2024 14:18:21 GMT | [{"Namespace":"","Key":"class","Val" |
|          |                               | :"mtime"}]                           |
| td       | Wed, 21 Aug 2024 14:13:54 GMT | [{"Namespace":"","Key":"class","Val" |
|          |                               | :"mtime"}]                           |
| td       | Wed, 21 Aug 2024 14:15:45 GMT | [{"Namespace":"","Key":"class","Val" |
|          |                               | :"mtime"}]                           |
| td       | Mon, 16 Sep 2024 13:51:08 GMT | [{"Namespace":"","Key":"class","Val" |
|          |                               | :"mtime"}]                           |
+----------+-------------------------------+--------------------------------------+
</pre>

My anyquery: anyquery version 0.1.3 (built with go1.22.6 for linux/amd64)

**Comment by julien040** [comment]
Thank you for reporting this, @marcoarthur.  
The issue will be fixed in the next release.  

I'll ping you when I release it.

**Comment by julien040** [comment]
Hey @marcoarthur, this should be fixed in `0.2.1`. Could you check if it's fixed?

P.S. The `read_html` table [caches data for 60s](https://anyquery.dev/docs/usage/querying-files/#html). If you're often refreshing `localhost:8000`, that might be an issue. You can disable caching by adding `cache_ttl='0'` to the table arguments.
