### ISSUE TITLE
Error while installing plugins - Snapcraft

### ISSUE THREAD

**Issue by RedHotUnicorn** [julien040/anyquery#21]
Hello!

trying to install notion plugin:
```bash
anyquery install notion 

Error: could not update the registries: could not load the default registry: 
error downloading registry: error downloading registry from https://registry.anyquery.dev/v0/registry/: 
Get "https://registry.anyquery.dev/v0/registry/": 
dial tcp: lookup registry.anyquery.dev on [::1]:53: dial udp [::1]:53: socket: permission denied

```
version

```bash
anyquery -v
anyquery version 0.2.2 (built with go1.23.0 for linux/amd64)
```

the resource https://registry.anyquery.dev/v0/registry/ is also accessible from web.

**Comment by julien040** [comment]
Hi @RedHotUnicorn, I'm sorry this is happening. This seems to be a DNS issue. Can you check if the registry is accessible from curl? (I don't know if you tried to access the registry from a browser or from the terminal.)

```bash
curl "https://registry.anyquery.dev/v0/registry/"
```

If it works, can you try manually updating the registry?
```bash
anyquery registry refresh
```

If this command fails too, are you using a custom DNS provider? Are you from a country that bans Cloudflare? I'm sorry, I can't figure out where the issue might be coming from.

**Comment by RedHotUnicorn** [comment]
Hello!

Yeah from wget, curl everything seems to be fine:
```bash
wget https://registry.anyquery.dev/v0/registry/ -O anyquery_registry.json
curl "https://registry.anyquery.dev/v0/registry/"
```

strange thing that there is no registry at all in:
```bash
anyquery registry list
+------+-----+----------+-------------+-----------------------+
| Name | URL | Checksum | Last Update | Last check for update |
+------+-----+----------+-------------+-----------------------+
+------+-----+----------+-------------+-----------------------+
0 results

```
About DNS : using standard one.
I think no bans appears because I can reach out url by curl and web.

I think there is no possibility to add registry from file, right?

btw: thank you for such elegant and powerfull tool.
Like it

**Comment by julien040** [comment]
Thanks ! You're right, this is not a network issue.
I've no idea where this bug might be coming from.

In the meantime I fix the issue, can you try adding the registry manually?
```bash
anyquery registry add default https://registry.anyquery.dev/v0/registry/
```

**Comment by RedHotUnicorn** [comment]
@julien040 I think I found a workaround.

The issue was with version with snap package.
I tested it on two Ubuntu servers with snap. 
Both gave me error.

But on mac it works.
And also it works on Ubuntu if install from `deb` package from release page.

**Comment by julien040** [comment]
Thank you @RedHotUnicorn!  
Snapcraft is definitely the issue. I've been able to reproduce the issue

```bash
root@ubuntu-s-2vcpu-2gb-amd-fra1-01:~ snap install anyquery
2024-10-14T19:48:58Z INFO Waiting for automatic snapd restart...
anyquery 0.2.2 from Julien Cagniart (julien040) installed
root@ubuntu-s-2vcpu-2gb-amd-fra1-01:~ anyquery install calendar
Error: could not update the registries: could not load the default registry: error downloading registry: error downloading registry from https://registry.anyquery.dev/v0/registry/: Get "https://registry.anyquery.dev/v0/registry/": dial tcp: lookup registry.anyquery.dev on [::1]:53: dial udp [::1]:53: socket: permission denied
```

I'm an idiot; `snap` uses a [confinement](https://snapcraft.io/docs/snap-confinement) system for additional security. But I've completely forgotten to configure it, so it refuses any network or file system access. As a workaround, please install anyquery using `deb`. Sorry for the inconvenience.

[https://anyquery.dev/docs#ubuntu-debian-and-derivatives-apt-package-manager](https://anyquery.dev/docs#ubuntu-debian-and-derivatives-apt-package-manager)

**Comment by julien040** [comment]
Update: I wasn't able to move Anyquery to the classic confinement. Therefore, I'm dropping support for Snapcraft.
