### ISSUE TITLE
osquery tables

### ISSUE THREAD

**Issue by gedw99** [julien040/anyquery#23]
Would like to see os query style plugins.

https://github.com/osquery/osquery

This will allow us to monitor servers .

**Comment by julien040** [comment]
Hello @gedw99,
I'm not sure that duplicated code is a good idea. [Osquery](https://github.com/osquery/osquery) is already a mature project of the Linux foundation.

But for basic use cases (e.g., listing processes, opened ports, listing disks), yeah, that would be cool. I've already written [a guide on creating a plugin](https://anyquery.dev/docs/developers/plugins/create-plugin/). You could probably implement some of Osquery's tables.

**Comment by julien040** [comment]
Didn't know about this library @gedw99, but it matches exactly what I was imagining for the plugin. Thank you for the find! I would love to see this library exported as Anyquery tables.

**Comment by julien040** [comment]
Hello @gedw99, see https://anyquery.dev/integrations/system.

Hope this helps!
