### ISSUE TITLE
Terminal output is not aware of width

### ISSUE THREAD

**Issue by archiewood** [julien040/anyquery#4]
Cool project! 
I'm pretty interested in something like this for counting GH stars or similar for open source projects

Tested with Github

Result is difficult to read

- MacOS:  Sonoma 14.2.1
- Terminal: Version 2.14 (452)
- Anyquery 0.1.2

![CleanShot 2024-08-09 at 18 55 10](https://github.com/user-attachments/assets/6e996366-50d5-4050-a84a-dc45ed92af14)

**Comment by julien040** [comment]
Hi, yes it's a known issue.

Anyquery is aware of the terminal width but when there are too many columns, it can't perform well.
A width of 203 characters for 36 columns leaves only 5.6 characters per column.

I honestly don't know how to fix that. If I remember correctly, DuckDB shows ellipsis. But that would truncate output sometimes. Or maybe anyquery should print a warning message.

In the meantime, you can try to print fewer columns or print in a format with less width such as `json` or `linebyline`. To do so, run `.format [format name]` in the shell.
Sorry for not being able to fix it

**Comment by archiewood** [comment]
yeah duckdb's "duckbox" output implementation is quite nice, they truncate some of the middle columns and show first and last up to the width

**Comment by julien040** [comment]
Hi @archiewood,  
I've finally fixed this issue.

![Sl55Ioet](https://github.com/user-attachments/assets/5e423a51-5990-4666-af52-73028e434400)
