### ISSUE TITLE
build failure on darwin

### ISSUE THREAD

**Issue by gedw99** [julien040/anyquery#8]
```sh
anyquery % make
go build -o main.out -tags "vtable fts5 sqlite_json sqlite_math_functions" "-ldflags=-s -w" main.go
# command-line-arguments
/opt/homebrew/opt/go/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
ld: warning: ignoring duplicate libraries: '-lm'
ld: library 'prqlc-aarch64-apple-darwin' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

this is on main and latest tags

**Comment by julien040** [comment]
Hi @gedw99,
run `git pull` to fetch the latest changes. And retry `make`

Normally, the problem should be solved. It was due to not building the PRQL library using Rust. Now, dev builds default to not building PRQL.

**Comment by julien040** [comment]
About the ncurses library, thank you for the advice. It certainly looks interesting. But I feel like it's a matter of preferences.
I think I'll stick to mattn/go-sqlite3 for now, and if the need to migrate appears in the future, I'll make the changes. Anyquery already uses WAL mode, and WAL2 mode is still a development branch as far as I remember.

**Comment by julien040** [comment]
Hi @gedw99,
It should now be fixed. You probably updated go to the v1.23.0 which wasn't compatible before the [last commit](https://github.com/julien040/anyquery/commit/b55691635873367c81a13d29393035594241077f)

> Details
> Due to the disallowance of //go:linkname, some packages weren't working anymore.
> Vitess has been bumped to the main branch and Parquet to v0.23.0.
